id: amazon-docker-config

info:
  name: Dockerrun AWS Configuration Exposure
  author: pdteam
  severity: medium
 

requests:
  - method: GET
    path:
      - '{{BaseURL}}/Dockerrun.aws.json'
    matchers:
      - type: word
        words:
          - 'AWSEBDockerrunVersion'
          - 'containerDefinitions'
        condition: and
