id: configuration-listing

info:
  name: Sensitive Configuration Files Listing
  author: j33n1k4
  severity: medium
  description: directory listing of sensitive files
  reference: https://www.exploit-db.com/ghdb/7014
 

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config/"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Index of /configs"
          - "Parent Directory"
        condition: and

      - type: status
        status:
          - 200