id: debug-vars

info:
  name: Golang expvar Information Disclosure
  author: luqman
  severity: low
 

requests:
  - method: GET
    path:
      - "{{BaseURL}}/debug/vars"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"memstats":'
          - '"cmdline":'
        condition: and

      - type: status
        status:
          - 200