id: exposed-sharepoint-list

info:
  name: Exposed sharepoint list
  author: ELSFA7110
  severity: low
  reference:
    - https://hackerone.com/reports/761158
    - https://hackerone.com/reports/300539
 

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_vti_bin/lists.asmx?WSDL"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "GetListResponse"
          - "GetList"
        part: body
        condition: and

      - type: status
        status:
          - 200