id: ftp-credentials-exposure

info:
  name: FTP credentials exposure
  author: pikpikcu
  severity: medium
 

requests:
  - method: GET
    path:
      - "{{BaseURL}}/ftpsync.settings"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - FTPSync
          - overwrite_newer_prevention
          - default_folder_permissions
        part: body
        condition: and

      - type: status
        status:
          - 200