id: prometheus-exposed-panel

info:
  name: Prometheus.io exposed panel
  author: organiccrap
  severity: low
 

requests:
  - method: GET
    path:
      - '{{BaseURL}}/graph'

    matchers:
      - type: word
        words:
          - '<title>Prometheus Time Series Collection and Processing Server</title>'